# Development Configuration for China Multi-Lingual ASR System
# This configuration is optimized for development and testing

# Model Configuration
models:
  whisper:
    model_path: "/models/whisper-large-v3-ct2"
    compute_type: "float16"  # Use float16 for development
    device: "cuda"
    device_index: 0
  
  kimi:
    model_path: "/models/kimi-audio"
    torch_dtype: "bfloat16"
    device: "cuda"
    device_index: 0
    load_detokenizer: false

# Language Routing Configuration
language_routing:
  confidence_threshold: 0.6  # Lower threshold for development
  supported_languages: ["zh", "en", "yue", "zh-tw"]
  kimi_languages: ["zh", "en"]
  fallback_engine: "whisper"
  detection_method: "whisper_encoder"  # whisper_encoder, custom_classifier, hybrid

# Performance Configuration
performance:
  max_concurrent_sessions: 10  # Lower for development
  encoder_batch_size: 1
  memory_optimization: false  # Disable for easier debugging
  enable_quantization: false  # Disable for development

# Server Configuration
server:
  websocket:
    host: "0.0.0.0"
    port: 9090
    max_connections: 10
    connection_timeout: 300  # 5 minutes
  
  api:
    host: "0.0.0.0"
    port: 8080
    enable_cors: true
    debug: true

# Audio Processing
audio:
  sample_rate: 16000
  chunk_size: 4096
  max_audio_length: 300  # 5 minutes max
  enable_vad: true
  vad_threshold: 0.5

# Logging Configuration
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/development.log"
  max_size_mb: 100
  backup_count: 5
  enable_console: true

# Monitoring and Metrics
monitoring:
  enable_metrics: true
  metrics_port: 8081
  enable_health_check: true
  health_check_interval: 30

# Development Features
development:
  enable_debug_endpoints: true
  enable_model_switching: true
  save_audio_samples: true
  audio_samples_dir: "debug/audio_samples"
  enable_performance_profiling: true
  mock_models: false  # Set to true to use mock models for testing

# Feature Flags
features:
  enable_integrated_asr: true
  enable_language_detection: true
  enable_custom_lid: false
  enable_word_timestamps: true
  enable_confidence_scores: true
  enable_fallback_routing: true 